### ISSUE TITLE
link-to-tabs - should have an option to open links in edit mode

### ISSUE THREAD

**Issue by pmario** [wikilabs/plugins#10]
see: https://groups.google.com/forum/#!topic/tiddlywiki/D_1lp8cMRuk

I am using $:/plugins/wikilabs/link-to-tabs in my info and to do list TiddlyWiki. Awesome.

But it bugs me that I have to do three steps to edit the tiddlers referenced by the tabs: 1) Click on the tab 2) Click on the link image on the tab to open the tiddler. 3) click to edit the tiddler. Since what the user wants to do is edit the tiddler (since she can already view the tiddler in the tab), it makes sense that clicking on the link image would open the tiddler in edit mode. That would reduce from three steps to two.

Pleasepleaseplease Mario: modify the plugin, or create a modified version of the plugin with this feature, as this would enhance this plugin!

**Comment by TiddlyTweeter** [comment]
I like the idea as an OPTION. I don't like the idea as some click combination or dropdown choice.

Use Cases: 
1 - I have a wiki that is heavily tabbed where I often need to see the Tiddler alone. NO editing access needed.
2 - I have a wiki with modest tabbing where I only ever edit the tabbed Tiddlers. Direct click access to the editor would save a click.

So, in my use cases, the click would work EITHER as open in view mode OR open in edit mode. User configurable. But NOT both. If you get my meaning?

Just a thought
Josiah

**Comment by pmario** [comment]
>... dropdown choice.

I try to avoid dropdowns at all cost.

**Comment by pmario** [comment]
>1 - I have a wiki that is heavily tabbed where I often need to see the Tiddler alone. NO editing access needed.

That's the default atm and it will stay that way. 

>2 - I have a wiki with modest tabbing where I only ever edit the tabbed Tiddlers. Direct click access to the editor would save a click.

link-to-tabs has the possibility to show all links at once. This already saves 1 click. -> no need to select the tab to activate the link button ... This setting will stay as it is. 

What I would like to add is an option which will be off by default, that allows a user to directly enter the edit tabs mode. ... 

TW already has the possibility to CTRL-Click links, that open tiddlers without scrolling them into the view. 
I intended to use the same mechanism. 

eg:

if the option: `1-click-edit` is active, 

 - clicking the tab-link button will open it in edit mode. 
 - CTRL-click will open the tiddler in view mode, with or without scrolling ... I'm not sure yet.

**Comment by pmario** [comment]
published: https://wikilabs.github.io/editions/edit-tabs/
