### ISSUE TITLE
Bundles with filters export empty

### ISSUE THREAD

**Issue by E-vd-H** [wikilabs/plugins#105]
Demonstration on Youtube of the bundler plug-in is done based on tiddler lists, where the list contains the full array of tiddler titles. When exporting with the button (1) in the sidebar, the one in the information of the tiddler under bundle (2) or the one in the advanced search (3), this results correctly in JSON or *.tid files that contain the information of these riddlers in the bundle.

However when doing the same thing with a filter, e.g. [tag[abc]] instead of the fully spelled out array of tiddler titles, only the button (3) in the advanced search is exporting the content correctly. The export button in the Sidebar (1) and the one in the Info field of the tiddler (2) result in an empty JSON string: i.e. [].
The same for TID exports.

I created the following tiddlers to demonstrate:
![Screenshot 2021-09-05 at 16 47 22](https://user-images.githubusercontent.com/10284179/132131137-ab1a4eac-0200-4e19-93ba-9c933f50f5bb.png)

When I now try to export these in a JSON, or TID file by the button ![Screenshot 2021-09-05 at 16 52 00](https://user-images.githubusercontent.com/10284179/132131232-3c28f3ab-747f-454d-b865-eee2850a69bb.png) on the left or the right, 

![Screenshot 2021-09-05 at 16 51 54](https://user-images.githubusercontent.com/10284179/132131688-78741d93-c167-4ccc-8bd5-f7fcbc9a28b7.png)

I get an empty file:
![Screenshot 2021-09-05 at 16 55 31](https://user-images.githubusercontent.com/10284179/132131386-4fd3ce97-e736-4b07-a5ee-7de0604b9f8c.png)

Doing the same with the Advanced Search export, by first selecting to open the list in the Advanced Search
![Screenshot 2021-09-05 at 16 59 09](https://user-images.githubusercontent.com/10284179/132131454-10a3ab3d-a139-412c-b9a0-5240da1f0c46.png) and then selecting the export button

![Screenshot 2021-09-05 at 17 01 00](https://user-images.githubusercontent.com/10284179/132131519-8c819a96-d53d-4a61-8fe2-705a1a5f673b.png)

results in the expected result (content wise, except for the name of the export file)
![Screenshot 2021-09-05 at 17 02 11](https://user-images.githubusercontent.com/10284179/132131567-2d82b789-6512-42c1-9b28-87e8639b5620.png)

**Comment by pmario** [comment]
Hi, Thanks for the feedback. But I think you need to enable filtered bundles. .. The bundled list can not work with [tag[abc]] in it. ... I did mention a new video for filtered bundles, but I didn't do the video yet. ... Sorry

Filtered bundles are enabled with: 

![grafik](https://user-images.githubusercontent.com/374655/132136041-2853e15a-8e78-4ba3-b6fa-e715c8d7ef93.png)


The configuration has to look like this: 

![grafik](https://user-images.githubusercontent.com/374655/132135988-df777318-c1d5-475c-b155-419d37294a4f.png)

**Comment by pmario** [comment]
@E-vd-H Eric, I do have to think about some improvements in the UI, since it shouldn't be happen that users are confused like that. ... It needs to be more obvious that filtered bundles need to be enabled. ... 

There are 2 different settings, because "filtered bundles" are compatible with the dropdown list in the Advanced Search tab. .. so if you create a "test" configuration and you have a look at the Advanced Search dropdown, it will be there.

**Comment by E-vd-H** [comment]
Thank you Mario. To me that was not so clear indeed. 
I tried it out in this way and I can confirm that with this explanation everything works as intended.

I will close the issues now and I thank you as well for all the good work in the last decade that you provided the community.
Take care.
