### ISSUE TITLE
Confused: Custom-Markup doesn't update ...

### ISSUE THREAD

**Issue by TiddlyTweeter** [wikilabs/plugins#109]
Inside a wiki I attempt to update CM to v. 0.22.0 using your update tool. BUT the plugin remains at v 0.21.3 after pressing "update" and reloading. Am I doing something wrong??

![Screenshot 2021-12-21 122143](https://user-images.githubusercontent.com/28830541/146922408-93df23e8-5d54-41ad-892f-b67cb59693ae.jpg)

**Comment by pmario** [comment]
Will need to test it. ... In the meanwhile you can delete and re-install the plugin as a workaround

**Comment by pmario** [comment]
Which TW version do you use?

**Comment by pmario** [comment]
Sorry -- 0.21.3 is the latest version. ... It seems the overview setting in the library has picked up the next upcoming version, which I can't publish atm, since it seems to create a performance hit.

**Comment by TiddlyTweeter** [comment]
> Sorry -- 0.21.3 is the latest version. ... It seems the overview setting in the library has picked up the next upcoming version, which I can't publish atm, since it seems to create a performance hit.

Thanks for letting me know!

**Comment by TiddlyTweeter** [comment]
I'm gonna close this as it effectively solved/explained.

Best, TT
