### ISSUE TITLE
Unexpected behaviour for two settings

### ISSUE THREAD

**Issue by twMat** [wikilabs/plugins#120]
(Sorry for bad headline but temporary lack of imagination)

Comments on two settings:

**Enable Overwrite Check** - this seems to be active by default already in TW, without the bundler plugin. E.g this is from *empty.html*, without any plugin installed:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/4534056/160922094-eaa370db-5cef-46c5-b057-a1d16fccb21a.png">

**Rename Title on Import**
On your [bundler demo site](https://wikilabs.github.io/editions/bundler/#%24%3A%2Fplugins%2Fwikilabs%2Fbundler%2Fui%2FControlPanel%2Fbundler-config) I was expecting the following setting to make it so that pasting an image from clipboard would set the title to be `xxxxx` but it is still `image.png`. Am I doing something wrong?

<img width="601" alt="image" src="https://user-images.githubusercontent.com/4534056/160922775-7db92334-5862-49c0-983c-2f557d51583d.png">

**Comment by pmario** [comment]
The template is used to create the new name. The first parameter is the name of the image from the clipboard.

The first parameter is "image.png" or "grafik.png" in my browser, since my FF talks German to me.

**Comment by pmario** [comment]
The overwrite check is "off" by default

**Comment by pmario** [comment]
The next version will have better info. ... I hope ;)

![image](https://user-images.githubusercontent.com/374655/210451368-7518b2d1-8e9c-490b-8af0-3b5835b5df49.png)
