### ISSUE TITLE
[BUG] Tab (button) content is deleted when advanced search is repeated 

### ISSUE THREAD

**Issue by CodaCodr** [wikilabs/plugins#135]
### Describe the bug

I host a copy of the advanced search tabs elsewhere in my wiki.

![image](https://user-images.githubusercontent.com/436812/212544996-f8321938-4758-42b3-abdb-832619ae3c1f.png)

When AS+ is installed, the second copy of AS loses the text from the tab-buttons:

![image](https://user-images.githubusercontent.com/436812/212545051-537dcc04-cbd9-425a-b074-47d009979535.png)

The regular AS is unharmed:

![image](https://user-images.githubusercontent.com/436812/212545086-b823920b-7835-445d-ad42-e725204df67d.png)

### TiddlyWiki Configuration

TW 5.2.5
Firefox latest
Win10

**Comment by pmario** [comment]
hmm. How does your Find tab content look like? can you post the code from the Find tab?

**Comment by CodaCodr** [comment]
If I recall, I just snagged it from TW (quite some time ago).

```
<div class="tc-advanced-search">
<$macrocall $name="tabs" class="bk-tw-advanced-search"
 tabsList="[all[shadows+tiddlers]tag[$:/tags/AdvancedSearch]!has[draft.of]]" 
 default="$:/core/ui/AdvancedSearch/System" 
 actions="""<$action-setfield $tiddler="$:/state/advancedsearch/currentTab" text=<<currentTab>>/>""" 
 />
</div>
```

I tried it on the demo site, too:

![image](https://user-images.githubusercontent.com/436812/212564727-7e8c932c-4205-47b7-bc3c-9d66d5e85d7a.png)

Then I tried it live on TW .com - same result.

**Comment by CodaCodr** [comment]
![image](https://user-images.githubusercontent.com/436812/212565298-776b8722-4c80-42c0-a382-0e1507c5442e.png)

**Comment by pmario** [comment]
IMO that's the wrong code. If you want the ASP buttons you need to use the button template that comes from the plugin

```
\whitespace trim
<div class="tc-advanced-search">
    <<tabs tabsList:"[all[shadows+tiddlers]tag[$:/tags/AdvancedSearch]!has[draft.of]]" default:"$:/core/ui/AdvancedSearch/System" 
        buttonTemplate:"$:/plugins/wikilabs/advanced-search-plus/TabButtonTemplate" explicitState:"$:/state/tab--1498284803">>
</div>
```

**Comment by CodaCodr** [comment]
Got it. Thanks Mario!
