### ISSUE TITLE
advanced-search: filter-dropdown is hidden under story-river

### ISSUE THREAD

**Issue by pmario** [wikilabs/plugins#14]
see: https://groups.google.com/d/msg/tiddlywiki/tWo3S6sEwTs/fUmAB5EeCQAJ

When you use the drop down list of filters, it extends to the left UNDER the tiddler river. making the titles pretty much impossible to see.

**Comment by Jermolene** [comment]
Can you post a picture? I'm not sure what you're describing, and that's a long thread.

**Comment by pmario** [comment]
I think that's solved by the core
