### ISSUE TITLE
[Feature request] Use mode text/vnd.tiddlywiki for bundles while still displaying as list 

### ISSUE THREAD

**Issue by Marxsal** [wikilabs/plugins#143]
### Describe the bug

Currently bundles are stored in text mode.

If you rename a tiddler, you can't depend on relink to rename the tiddler in the bundle because it won't process text tiddlers.

If you change the bundle type to text/vnd.tiddlywiki, then relink will work inside the bundle. But the list will not display nicely.

What would be ideal is if the bundles could use text/vnd.tiddlywiki, but the display view would still show a nicely formatted list.

### TiddlyWiki Configuration

TW files using relink to maintain links.

**Comment by pmario** [comment]
I'll have a look if bundler can use the view template body cascade to show text/plain instead of text/vnd.tiddlywiki, then relink would work in the normal way.

**Comment by Marxsal** [comment]
Relink has really extensive configuration, but when it comes to tiddler types, not so much:

> By default, Relink treats the text body of most tiddlers as [Wikitext](https://github.com/wikilabs/plugins/issues/143#Wikitext). This includes all tiddlers that don't have a type field, or have a type field of text/vnd.tiddlywiki. However, different type fields will be relinked differently. For instance, Relink will ignore the text bodies of all text/plain tiddlers, because plain text doesn't have any links or references.

**Comment by Marxsal** [comment]
Test ... what? Is there new code somewhere? The newest repository entry is from a month ago.

I just did a quick test, and adding the code-body field does not interfere with relink, if that is the question.

Thanks!

**Comment by pmario** [comment]
If you remove the type-field and set code-body:yes  -- then relink should work as expected. 

I'm working with bundler atm. Switching from v0.5.2 to v1.0.0 and adding 

Done: 

**Simple story related functions**

![image](https://github.com/wikilabs/plugins/assets/374655/3b28736e-64bb-4c2a-b601-0416adbdf6fe)

** A bit more info in the ViewTemplate for filtered bundles** 

![image](https://github.com/wikilabs/plugins/assets/374655/63c47928-913b-4a46-81b7-a5852e2b5f93)


ToDo

- Configuration for visible buttons in the Bundler sidebar tab

**Comment by pmario** [comment]
bundler V1.0.0 should do this: https://talk.tiddlywiki.org/t/intro-bundler-plugin-allows-you-to-create-export-import-configurations-and-save-them-as-a-bundle/5958/4?u=pmario
