### ISSUE TITLE
[BUG] When using FIREFOX, Bundler Plugin provokes a Javascript Error: Permission denied to access property 'script' 

### ISSUE THREAD

**Issue by JulioCantarero** [wikilabs/plugins#156]
### Describe the bug

When I navigate to the [Bundler Plugin demo site](https://wikilabs.github.io/editions/bundler/) using the Firefox browser, I get a pop-up Javascript Error: Permission denied to access property 'script'. I have the same problem with my own TiddlyWiki on node.js installation in my local PC, also using Firefox browser. I am running everything in a Windows 11 PC.
The problem does not happen with Chrome or Edge.

### Expected behavior

The error should not be appearing. I think the cause is the Bundler Plugin because it does not happen in https://tiddlywiki.com/, but it does in the [Bundler Plugin demo site](https://wikilabs.github.io/editions/bundler/), which only has TW and the plugin.

### To Reproduce

1.Open [Bundler Plugin demo site](https://wikilabs.github.io/editions/bundler/) in the Firefox browser in a Windows PC

### Screenshots

![screen_20241001_085346](https://github.com/user-attachments/assets/880b842d-8d42-4cb3-8b16-17d0314d6e38)

### TiddlyWiki Configuration

-Your own config in [Bundler Plugin demo site](https://wikilabs.github.io/editions/bundler/)

**Comment by JulioCantarero** [comment]
I just realized that this error in Firefox is happening in other TiddlyWiki pages, even in https://tiddlywiki.com/.
Maybe the root cause is not within the Budler plugin as I initially thought.
If you conclude the budler plugin is not to blame, please close the bug.
I forgot to mention: it has no effect whatsoever. Once you dismiss the Error pop-up, everything works fine.

**Comment by pmario** [comment]
Thanks for the feedback. But I can not replicate that problem. Once I do publish a new version I do visit all my demo pages for a short test. I exclusively use FireFox.

So I think it may be one of your browser AddOns. Did you test the page with a new browser profile or plugins disabled?

**Comment by pmario** [comment]
You can test it the Dev-Tools F12 -> Debugger -> Breakpoints -> [x] Pause on exceptions -> F5 or reaload page

![image](https://github.com/user-attachments/assets/fb920998-be99-4def-86c5-ef102888da53)

**Comment by JulioCantarero** [comment]
Hi Mario.
Thank you for the hint. You were absolutely right. The problem disappears when I disable the Firefox plugin "Open in Chrome" (https://webextension.org/listing/open-in.html?from=chrome).
The funny thing is that the error pop-up only appears when I browse some TIddlyWiki pages. That is why I thought it was related. But I acted in a haste opening a bug, without checking more thoroughly. Sorry about that.
BTW, your TW plugins are terrific and very useful. Thank you!
