### ISSUE TITLE
advanced-search-plus: Add Button to open the interface in the Story River

### ISSUE THREAD

**Issue by TiddlyTweeter** [wikilabs/plugins#16]
This issue arises from a [GG comment](https://groups.google.com/d/msg/tiddlywiki/tWo3S6sEwTs/66CeKxe_CQAJ).

Though I know the idea is the a-s-p tool is in the sidebar, I think one enhancement could be to _add a button to the be able to open it in the Story River_ if needed. Useful for serious searches with long result lists. It might also function better that way on Mobiles?

**Comment by pmario** [comment]
As mentioned. One option would be https://wikilabs.github.io/editions/link-to-tabs/ plugin. ... But I'll have a closer look.

**Comment by TiddlyTweeter** [comment]
> As mentioned. One option would be https://wikilabs.github.io/editions/link-to-tabs/ plugin. ... But I'll have a closer look.

@pmario, thanks for giving it consideration.  Just so you know my background thought ...

(1) ... its a _design issue that is partly just a matter of taste_. But I do feel the sidebar is overwhelmed as a design with everything in it :-) We need a "sidebar thinning programme" ? :-) Its hard to shine cramped in two column inches. For instance, when I took Explorer out of the sidebar I realised how good it is and I use it widely now in tiddlers.

(2) ... specifically on mobiles, if you look at the current better designs, the sidebar is problematic. It usually gets orphaned from the context of the story river. You can't see what is going on.

In brief, I think your tool needs space :-)

**Comment by pmario** [comment]
:) I do have much space. I work with a 34" wide screen monitor, where 2 open programs can stay there the whole day, without resizing them. So TiddlyMap looks like this :)

![screenshot](https://user-images.githubusercontent.com/374655/53493578-ed794380-3a9b-11e9-9fa4-dcb3e3b4812d.gif)

**Comment by pmario** [comment]
You know, that the core AdvancedSearch button, right beside the search area opens the $:/AdvancedSearch tiddler, which is the same as in the sidebar.

**Comment by pmario** [comment]
see: https://wikilabs.github.io/#%24%3A%2FAdvancedSearch

**Comment by pmario** [comment]
There are 2 possibilities to achieve this result.

The core AdvancedSearch button and 
The [link-to-tabs plugin](https://wikilabs.github.io/editions/link-to-tabs/)

![image](https://user-images.githubusercontent.com/374655/215202548-07d01896-bde7-4416-8d8e-c0924ee3721f.png)
