### ISSUE TITLE
uni-link: strange behavior with `&` aliases

### ISSUE THREAD

**Issue by diego898** [wikilabs/plugins#19]
I think there is a bug in the following situation:

If you go to the [demo site](https://wikilabs.github.io/editions/uni-link/) and make the following 4 tiddlers:

* Test1
  * this is an alais to [[TT|?]]
* Test2
  *  this is an alais to [[NN&TT|?]]
* Test Title
  * aliases: TT
* New Title and Test Title
  * aliases: NN&TT

Then the `New Title and Test Title` tiddler thinks that **both** `Test1` and `Test2` are aliasing to it. 

This came up for me because I have a topic aliased to `OT` another topic called `AB` and another tiddler called `Connection between OT and AB` that I aliased to `AB&OT`.

**Comment by pmario** [comment]
are you sure, you have the latest plugin version? .. Did just test it with https://wikilabs.github.io/editions/uni-link/ and it seems to work

**Comment by pmario** [comment]
uups ... It's the InfoPanel: References tab, that seems to have a problem. ...

**Comment by pmario** [comment]
I think I found it. ... Some more tests needed :) Will publish a new version soon!
thx for the feedback!

**Comment by pmario** [comment]
@diego898 https://wikilabs.github.io/editions/uni-link/ should be up to date now. please test! 

sry for the delay ... but the whole setup still needs too much manual steps.

**Comment by diego898** [comment]
Hey @pmario thanks for the fix! I can confirm that that this version fixes the & bug
