### ISSUE TITLE
uni-link: feature requests - toggle use of `|?`and add aliases to search

### ISSUE THREAD

**Issue by diego898** [wikilabs/plugins#20]
Hey Mario,

Just wanted to make note of a feature request made in google group here:

- Remove/toggle necessity of `|?` marker. 
- Add aliases to search 

Note: [This is the original thread](https://groups.google.com/d/msg/tiddlywiki/pVqcVuNaTbA/aGfq6WsBAgAJ) where I asked for a couple more you said these more doable/considerable.

**Comment by pmario** [comment]
The next version will have an new editor-toolbar icon + a shortcut, that works similar to the include link `[[*]]` shortcut. eg: `[[|?]]`. I did some tests already and I think, this could be a good "workaround"

----------

I wanted to make the alias-link "as backwards compatible" as possible. ... If someone uses the `[[alias-pattern|?]]` with an "unmodified" TW, the link will point to the `?` tiddler. .. 

So users will immediately see, ther's something special. 

The expected response for this user would be, to ask the community, or the author, that provided the tiddler. 

If every `[[link]]` is an alias this feature would be gone. I would consider this a regression. ... So I would go with the button approach, and see if it works out.

**Comment by pmario** [comment]
See the new version, which adds UI improvements. 

> - Add aliases to search

is still a todo.

**Comment by pmario** [comment]
https://wikilabs.github.io/editions/uni-link/

**Comment by pmario** [comment]
There are several possibilities to add new fields to the search now. There is the new `search:fieldName` filter. 

I did some tests. 

# a) contains default list

![uni-link-search-01](https://user-images.githubusercontent.com/374655/52864013-86719b80-3139-11e9-98c9-1d899897bdac.gif)

# b) search every field except: title and text

![uni-link-search-02](https://user-images.githubusercontent.com/374655/52864019-896c8c00-3139-11e9-90c8-9a3f22732397.gif)

# c) same as a) and b) with advanced-search-plus plugin installed

![uni-link-search-03](https://user-images.githubusercontent.com/374655/52864023-8c677c80-3139-11e9-852d-6d50b4561503.gif)

What do you think? Should this be a plugin, or hardcoded into uni-link???

**Comment by pmario** [comment]
I did create a new plugin

**Comment by pmario** [comment]
@diego898 see: https://wikilabs.github.io/editions/field-search/

It's not perfect yet, but I think it's a good first step. Intro video is in the making!

**Comment by pmario** [comment]
@diego898 have a closer look at [GG](https://groups.google.com/forum/#!topic/tiddlywiki/Sxpx6Soj_7I) and the new [field-search-plugin](https://wikilabs.github.io/editions/field-search/)
