### ISSUE TITLE
The Bundler: Request bundles containing $:/state ... can be imported

### ISSUE THREAD

**Issue by TiddlyTweeter** [wikilabs/plugins#22]
This is just a note of your own comment on GG :-)

> The existing import mechanism doesn't import "$:/state.. " tiddlers. ... Which imo is an issue, but was implemented for a reason.
> 
> I'll check if the "bundler-plugin" can include an import-mechanism that allows us to import state-tiddlers.

**Comment by pmario** [comment]
see: https://groups.google.com/forum/#!topic/tiddlywiki/ZPaiDtpt1Zc

**Comment by pmario** [comment]
Will come with 0.2.0 ... soon ;)
