### ISSUE TITLE
The Bundler: Notes towards Docs -- Suggestions

### ISSUE THREAD

**Issue by TiddlyTweeter** [wikilabs/plugins#23]
Just a few suggestions to maybe add somewhere in the docs ...

-- A note making clear that you can Bundle tiddlers with any name into a JSON. BUT that tiddlers starting "$:/state" can't be imported into a receiving wiki due to the way TW works.

-- Maybe a tip, that if you have need for The Bundler, its useful to install it as the FIRST plugin in an empty TW as it will enable you to track Imports precisely.

-- If you know the settings you always want for The Bundler create a bundle (yes it can transport itself!) for it that includes any configuration Tiddlers you changed like: `$:/config/wikilabs/enableImportBundle` and `$:/config/wikilabs/enableBundles`

**Comment by pmario** [comment]
The next version of the bundler plugin should be able to import state tiddlers. ...

But yea, for standard TW it still will exclude states.

**Comment by TiddlyTweeter** [comment]
That is great news on possibility to import state tiddlers.

I don't think it matters at all on standard TW they are excluded as the non-import is for good reasons. Rather, someone using bundles is likely to have definite objectives and the choice to over-ride default import behaviour is an informed choice.

**Comment by pmario** [comment]
Version 0.2.0 will have a "Tips and Tricks" tiddler, which uses your info from here.
