### ISSUE TITLE
The Bundler: Note on the "Comment Prefix" -- It should be invariable

### ISSUE THREAD

**Issue by TiddlyTweeter** [wikilabs/plugins#24]
On GG I mentioned recently that it might be a good idea that the prefix for comments be user changeable. I want to make sure that you know I think, now, _that would be a mistake_ as it would break if anyone transported a bundle of mine into a system with a different comment prefix. ONE standard for comments is best, I think.

**Comment by pmario** [comment]
I came to the same conclusion. We need to establish a "standard" to get the thing compatible.
