### ISSUE TITLE
[markdown-it] colour of html links dont follow the colour pallet

### ISSUE THREAD

**Issue by hchaase** [wikilabs/plugins#28]
# this is for the markdown-it plugin

a html/external link in wikiText renders as:

`<a href="https://github.com/wikilabs/plugins/issues/new" class="tc-tiddlylink-external" target="_blank" rel="noopener noreferrer">https://github.com/wikilabs/plugins/issues/new</a>`

a html/external link in markdown-it renders as:

`<a href="https://github.com/wikilabs/plugins/issues/new">https://github.com/wikilabs/plugins/issues/new</a>`

As the class is missing, the colour cannot be controlled by the colour pallet (and if you have a dark background text becomes unreadable and this is a problem).

sry I don't know where in the code to fix this.

![billede](https://user-images.githubusercontent.com/2864323/48482443-f9a10400-e810-11e8-82a5-85d3927d91b3.png)

**Comment by pmario** [comment]
Hi, There seems to be a markdown-it plugin https://github.com/rotorz/markdown-it-external-links which would allow us to add custom classes. .... 

BUT I'm not sure if it would cover all our cases. Can you have a look if it would fit your usecase?

**Comment by pmario** [comment]
Didn't get feedback. -> close.
