### ISSUE TITLE
bundler should implement a "bulk delete" option

### ISSUE THREAD

**Issue by pmario** [wikilabs/plugins#3]
bundler should implement a "bulk delete" option

see: https://groups.google.com/d/msg/tiddlywiki/_Uqbg08Pjow/J5DHxzUVAgAJ

> On Monday, June 26, 2017 at 11:26:40 AM UTC+2, @TiddlyTweeter wrote:
I think the beauty of it is it eases export and import a lot in a minimal way. If somehow the same "Bundle List" could be passed to selectable delete it would make it a top-notch management tool IMO.
>
>The fact is import/export is a major gateway into and out-of a TW. It seems to me that explicit tracking of events around that are amongst the most important to be able to manage. The Bundler is the good step towards that.
>
>A Destroyer could put icing on the cake. 

I like that name :) ... I would need to have a closer look. I want to user functions, that are "out of the box" as much as possible.
So we'll see. ...

**Comment by TiddlyTweeter** [comment]
Thanks for noting that! Josiah.

**Comment by pmario** [comment]
note: 

 - It should show a selectable list of tiddlers, that should be deleted. 
 - The different elements are already selected
 - The menu may be More: Prepare Bulk Deletion ... or so

**Comment by pmario** [comment]
Bulk delete for filtered bundles can be done with the "test-button", which switches to the AdvancedSearch : Filter tab
This tab has a "Bulk Delete" button

This will be part of the docs in 0.2.0

**Comment by pmario** [comment]
V0.2.0 has the new tab in the tiddler-info area, which allows a "single delete" action.
simple "list bundles" will get an "Open in AdvancedSearch" button, to get access to bulk delete
