### ISSUE TITLE
Feauture Request: Change References Language

### ISSUE THREAD

**Issue by diego898** [wikilabs/plugins#30]
Hey @pmario,

In my local wiki, I changed the content of `$:/core/ui/TiddlerInfo/References` in unilink so that the empty message is specific to aliases like so:

```
<$list filter="[all[current]aliasbacklinks[]sort[title]]" emptyMessage="No tiddlers alias to this one" template="$:/core/ui/ListItemTemplate"></$list>
```

It no longer uses the lingo macro, but it has been very useful to me.

**Comment by pmario** [comment]
Will be fixed (english text) in the next version
