### ISSUE TITLE
markdown-it Include an image using Markdown

### ISSUE THREAD

**Issue by luffe0601** [wikilabs/plugins#32]
see https://groups.google.com/forum/#!topic/tiddlywiki/P5fYxLIlk8k

tiddlywiki 5.1.9
plugins/wikilabs/markdown-it version 0.1.0
i disable plugins/tiddlywiki/markdown, if use it, the image display correctly.
but i still like to use gfm.

Thanks :)

**Comment by pmario** [comment]
The markdown-it plugin has no info about images included into a single wiki file. 
It may work with links like: `![alt-text](https://image-url.jpg)`

**Comment by pmario** [comment]
got no feedback. Tested it locally and it works as expected using the markdown link syntax.
