### ISSUE TITLE
Unilink - Shows title twice

### ISSUE THREAD

**Issue by diego898** [wikilabs/plugins#39]
Hey Mario,

I just upgraded to 5.1.20, and now links like:

`[[My Essays]]` show up as:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/742407/62893950-520a2100-bd11-11e9-8239-926cb36cdaaa.png">

`My Essays` has no subtitle, caption, or alias.

**Comment by pmario** [comment]
the plugin is flagged "-experimental" in the version number. ... So if you give your OK, I'll publish it, without this flag.

**Comment by diego898** [comment]
Hey @pmario - things look good for me with this version (so far). I will report back if I find anything. Thanks!

**Comment by pmario** [comment]
I did post the official version a view minutes ago. Thx for your feedback
