### ISSUE TITLE
The Bundler: Internal Documentation Issues

### ISSUE THREAD

**Issue by TiddlyTweeter** [wikilabs/plugins#4]
The Bundler works really well. My only issue is I really would like to be able to document what's in a bundle without it throwing off the count ... At the moment I add lines like ...
       `[[--- COMMENT ---]]`
... before items to explain what they are. Its economical & informative. But it throws off the Bundle Count. Users receiving it may well get confused. I also have to double check and subtract the "comment" lines manually in my head to be sure I have the Bundle Count correct.

Best wishes
Josiah

**Comment by pmario** [comment]
I think I found a solution for this problem. 

IMO we could use the existing `.multids` format, which knows comments that start with `#`. .. The only problem is the `enlist` operator doesn't know about the `application/x-tiddlers` format yet. 

So we would need to expand the core or create something "special" for the plugin.

**Comment by pmario** [comment]
Other possibilities, that just came to my mind: http://tiddlywiki.com/#ViewWidget:ViewWidget%20DictionaryTiddlers%20DataTiddlers 

... just a reminder

**Comment by TiddlyTweeter** [comment]
Thanks for the update. I can't help you on the technical side since I don't understand it. But just want to express my gratitude as the Bundler is an incredibly useful tool.

Maybe a bit later I can help you document it with some Use Case examples? That I can do.

**Comment by pmario** [comment]
Will come with 0.2.0
