### ISSUE TITLE
It seems that "tocP-tabbed-internal-nav" with custom field doesn't work

### ISSUE THREAD

**Issue by hexawing** [wikilabs/plugins#47]
![screen](https://user-images.githubusercontent.com/230037/91634522-a28b1400-ea23-11ea-9a08-b2910182bf59.png)

If I use "parent", it works well.
But if I use "z_parent" or other field name, it doesn't work.

**Comment by pmario** [comment]
Sory for the late reply. .. I'll look into it today.

**Comment by pmario** [comment]
The latest version seems to work. 

![image](https://github.com/wikilabs/plugins/assets/374655/2873743b-03b9-4b64-86bb-ddf937683da6)

So close this one.
