### ISSUE TITLE
Comment On _use="[Glyph+String]"

### ISSUE THREAD

**Issue by pmario** [wikilabs/plugins#65]
### Comment On _use="[Glyph+String]" 

I'm interested in the "**_use=**" mechanism. _Why?_ Because you can create TWO different ways to acheive the same markup. That is VERY useful for cases where the end-user needs clarity, when they first start, that the Markup they enter is "semantically explicit" ... For example, you can make a TW for poetry that is easy. Normal users (AT FIRST) will want to enter this ...
```
»POEM Here is a poem
Here is a line
«POEM
```
We can easily support that via ...
```
\\ POEM ----------------------------------
\customize angle='POEM' _endString='«POEM' _element='div' _classes='.poem-strict' _mode='block'
```
But LATER they will want to type using the COMPACT method like this ... :-)
```
»§ Here is a poem
Here is a line
«§
```
... so I tried re-assignment of "»POEM", to give an additional method, like this ...
```
\\ POEM: shorthand -----------------------
\customize angle=§ _use=POEM _endString='«§'
```
It works WELL. But the ISSUE is that **_use=** change does _not_ allow change to _**endString=**'«§'.
This limits its use to cases where there is NO _endString OR the _endString stays the same?

_Yes?_

_Originally posted by @TiddlyTweeter in https://github.com/wikilabs/plugins/discussions/62#discussioncomment-400653_

**Comment by pmario** [comment]
@TiddlyTweeter I kind of knew something like this would come up as I did play with the `_use` parameter. I also was limited, but I couldn't figure out a usecase, that was valid and "blocked" by the limitations.

You did find a really good reason to look at the implementation again. 

The problem is, that I'll need to rewrite the "debug" mechanism, to show the whole config. Otherwise it may be difficult to see, what's going on. eg: `_use=x _debug=xxx` should show the all pragma configs that are involved.

**Comment by TiddlyTweeter** [comment]
Well, @pmario, I can live with it fine as it is. I just  won't use **_use=** as it is. Mainly because my use cases that would use it need the **_endString=** part. BUT we can still have more than one pragma for a markup, so it is not a decisive issue.

**Comment by TiddlyTweeter** [comment]
### Your _use="[Glyph+String]"  update ...

Just FYI. I will actively test this as it is a very useful feature to be able to re-assign "CM rules" to new ID's.

**Comment by pmario** [comment]
Yea, but you have to be careful. I think redefining 1 parameter is OK, but as soon as you change more than 2 IMO it would be better to create a new pragma on it's own. ... Especially if you use _useGlobal. ... It will make the lookup a bit tricky. ..

There is a `_useGlobal` for quite a while, which I forgot to document :) ... 

The `_debug` parameter is also more flexible now. .. You can easily create a `_use=xxx _debug=both` without the need to modify the "original" pragma

**Comment by TiddlyTweeter** [comment]
> Yea, but you have to be careful. I think redefining 1 parameter is OK, but as soon as you change more than 2 IMO it would be better to create a new pragma on it's own. 

Right! Fully agree. The ONLY things I actually will ever need to change are the opening **ID** and the **_endString=**.

> There is a `_useGlobal` for quite a while, which I forgot to document :) ...

HaHa! I will take a look at what that is for.

> The `_debug` parameter is also more flexible now. .. You can easily create a `_use=xxx _debug=both` without the need to modify the "original" pragma

Excellent!

**Comment by pmario** [comment]
>(P.S. Also, for me, who needs consistency, it all needs doing in a way that makes clear logical sense. CM is SO rich in features that I do think I need to discipline myself so I don't get lost in a forest of flexibility.)

Yea, that's a "side effect". ... But we did have the same problem with TiddlyWiki at the alpha-days. ... New rules had to be created, new terms where invented and there was not too much documentation ;)

So once you are settled on your DSL syntax, you'll have to document for your "customers" and for yourself.

**Comment by pmario** [comment]
What do you think. Is custom-markup "feature complete" now?

**Comment by TiddlyTweeter** [comment]
> What do you think. Is custom-markup "feature complete" now?

It is the richest tool I've ever used in TW. 
As far as I can see its flexibility will let me do anything -**I**- need.

From MY point of view the ONLY issue left is really about presenting snippets in the editor. That is not a CM issue per se.
BUT in actual usage improving the way you access snippets actually matters quite a lot.

My 2 cents of today.

**Comment by TiddlyTweeter** [comment]
> @pmario: So once you are settled on your DSL syntax, you'll have to document for your "customers" and for yourself.

Right!

And actually good. Good in the sense that FINALLY you OWN your own system.

**Comment by TiddlyTweeter** [comment]
### Comment: In release, **V 0.11.3 - 2021-03-20**, I'm having issues with "**_use=**", including RSODs.

I have NOT been able to pin down exactly how to replicate the issue yet, but will test some more and report back.

**Comment by pmario** [comment]
I think I found it. The following causes a RSOD ... I'll try to fix it

```
\\ POEM ----------------------------------
\customize angle='POEMXXXX' _endString='«POEM' _element='div' _classes='.poem-strict' _mode='block' _debug=both

\\ POEM: shorthand -----------------------
\customize angle=§ _use=POEM _endString='«§' _debug=both
```

**Comment by pmario** [comment]
@TiddlyTweeter ... For issues like this, you should open a new issue. see:  #86

**Comment by TiddlyTweeter** [comment]
> @TiddlyTweeter ... For issues like this, you should open a new issue. see: #86

Yes. I should. But I don't like opening issues (creating work) unless I'm clear what they are and can explain them :-).

**Comment by pmario** [comment]
> Yes. I should. But I don't like opening issues (creating work) ...

If you would have created the issue, I wouldn't have to do it. ... So it actually would be "less work" ;) ... Anyway. It's easy to close issues, if they are not valid anymore. ... 

Creating them makes sure, that they are not forgotten. ... So if something looks like a bug, imo it would be more convenient to create an issue. .. 

On the other hand. if it is here, we know, that should probably be some documentation about .... something

**Comment by TiddlyTweeter** [comment]
> > Yes. I should. But I don't like opening issues (creating work) ...
> 
> @pmario  If you would have created the issue, I wouldn't have to do it. ... So it actually would be "less work" ;) ... Anyway. It's easy to close issues, if they are not valid anymore. ...

Point taken! TT
