### ISSUE TITLE
Field Search and Linkes-to-tab

### ISSUE THREAD

**Issue by kookma** [wikilabs/plugins#70]
It seems the clip by links-to-tab plugin displayed on field-search tabs is misplaced!

See screenshots

![image](https://user-images.githubusercontent.com/830394/111525118-7aba8e00-8772-11eb-874e-af4d67df4f30.png)

System info

- Chrome 89
- links-to-tab 0.1.1
- Field-search 0.4pre

**Comment by pmario** [comment]
link-to-tabs should be V2.01!

**Comment by kookma** [comment]
Hi Mario,
 I use links-to-tab 0.1.1 as it is the simplest and provide the nice link on every tab! But I will have a look at 2.0 and let you know the results!

**Comment by kookma** [comment]
I updated the link-to-tabs to the latest through wikilabs plugin library and now they work fine!

**Comment by pmario** [comment]
That's cool! The problem with link-to-tabs is, that I have to modify the tabs-macro. So if the core changes the macro, I'll have to update the plugin, to have the full functions.

TW V5.1.23 got a completely new keyboard handling for the tabs. So it's important to have the latest macro. 

The tabs macro already uses some templates. But I couldn't get it to work properly, only changing the templates. ... I'll have a closer look, probably coser to TW 5.1.24 release.
