### ISSUE TITLE
Improve the CM dropdowns - make then "STAMP" like

### ISSUE THREAD

**Issue by pmario** [wikilabs/plugins#75]
### Towards A "System", No 1 - STAMP Tool Snippets

I'm beginning to use CM is actual production systems. I am finding the STAMP tool a very good support for CM. 

For instance, the "Highlighters" I made at https://github.com/wikilabs/plugins/discussions/62#discussioncomment-409937 I made "prefix/suffix" snippets for that look like this ...

![Screenshot 2021-03-05 085800](https://user-images.githubusercontent.com/28830541/110085069-f2f77b80-7d90-11eb-9315-847c9dbec973.jpg)

Just an observation :-)

_Originally posted by @TiddlyTweeter in https://github.com/wikilabs/plugins/discussions/62#discussioncomment-431987_

**Comment by pmario** [comment]
All dropdown config files have changed the format!

See tags: `$:/tags/TextEditor/InlinePrefix` and `$:/tags/TextEditor/LinePrefix`

The "snippet elements" have  the same functionality as the buttons now. ... I'm investigating the possibility to select a snippet and use a keyboard shortcut afterwards. So it shouldn't be needed to open the dropdown again. 

![grafik](https://user-images.githubusercontent.com/374655/111867476-7eb5fe00-8974-11eb-8acc-5344933ba0f8.png)

**Comment by pmario** [comment]
Latest version 0.11.1 was uploaded several minutes ago. 
see: https://wikilabs.github.io/editions/custom-markup/

**Comment by TiddlyTweeter** [comment]
> Latest version 0.11.1 was uploaded several minutes ago.
> see: https://wikilabs.github.io/editions/custom-markup/

Great! I'll try test it out as soon as I can.

> I'm investigating the possibility to select a snippet and use a keyboard shortcut afterwards. So it shouldn't be needed to open the dropdown again.

Sounds good, if it is possible..

**Comment by TiddlyTweeter** [comment]
> @pmario I'm investigating the possibility to select a snippet and use a keyboard shortcut afterwards. So it shouldn't be needed to open the dropdown again.

I have been testing it out on your demo site. It is good, and far less confusing to understand what is going on than before.

ONE comment: Yes, IF the "stamps" could have _unique keyboard shortcuts of their own_  (one for inline stamper, one for block stamper) I think it would really help.

My 2 cents, TT
