### ISSUE TITLE
REQUEST: CM Stamp Tool Menus Have A `class`

### ISSUE THREAD

**Issue by pmario** [wikilabs/plugins#83]
### REQUEST: CM Stamp Tool Menus Have A `class`

@pmario, as in my example at https://github.com/wikilabs/plugins/discussions/62#discussioncomment-524524, the list of snippets would benefit if I could re-style the CSS. At the moment it is far too "visually noisy" because standard `<code>` is rendered in a way that is too obtrusive for the purpose there.

To do that, for all of them, in one-go, I'd need a wrapping CSS class, something like: `"wltc-snp"`.

I hope this is clear! Please ask if it isn't.
TT

_Originally posted by @TiddlyTweeter in https://github.com/wikilabs/plugins/discussions/56#discussioncomment-528317_

**Comment by pmario** [comment]
was simple to implement and will be part of V011.3

**Comment by pmario** [comment]
@AnthonyMuscio , @TiddlerTweeter https://wikilabs.github.io/editions/custom-markup/ V0.11.3 is online now

**Comment by TiddlyTweeter** [comment]
> was simple to implement and will be part of V0.11.3

Many thanks!

**Comment by TiddlyTweeter** [comment]
> @pmario  https://wikilabs.github.io/editions/custom-markup/ V0.11.3 is online now

Neat! I'll test over next couple of days. I see you've implemented several improvements ... great stuff!
