### ISSUE TITLE
custom-markup: example causes RSOD

### ISSUE THREAD

**Issue by pmario** [wikilabs/plugins#86]
```
\\ POEM ----------------------------------
\customize angle='POEMXXXX' _endString='«POEM' _element='div' _classes='.poem-strict' _mode='block' _debug=both

\\ POEM: shorthand -----------------------
\customize angle=§ _use=POEM _endString='«§' _debug=both

»§ Here is a poem
Here is a line
«§ 
```

**Comment by TiddlyTweeter** [comment]
Thanks for pinning that down!

> ```
> \\ POEM ----------------------------------
> \customize angle='POEMXXXX' _endString='«POEM' _element='div' _classes='.poem-strict' _mode='block' _debug=both
> 
> \\ POEM: shorthand -----------------------
> \customize angle=§ _use=POEM _endString='«§' _debug=both
> 
> »§ Here is a poem
> Here is a line
> «§ 
> ```

**Comment by pmario** [comment]
will look like this:

![grafik](https://user-images.githubusercontent.com/374655/112841287-9a21b700-90a0-11eb-96a7-4a55e381f372.png)
