### ISSUE TITLE
I think I'll implement _3 and _4 but _not_ documenting it.

### ISSUE THREAD

**Issue by pmario** [wikilabs/plugins#87]
I think I'll implement _3 and _4 but _not_ documenting it.

_Originally posted by @pmario in https://github.com/wikilabs/plugins/discussions/56#discussioncomment-543560_

**Comment by TiddlyTweeter** [comment]
I think that is a good approach, to not document it. 
Knowing _3 & _4 are available MAY help me in some very rare cases. 
But I think it will be rare that I'd actually really need them.
