### ISSUE TITLE
custom-markup: issue presenting snippets in the editor

### ISSUE THREAD

**Issue by pmario** [wikilabs/plugins#90]
From MY point of view the ONLY issue left is really about presenting snippets in the editor. 
This is not a CM issue per se.
BUT in actual usage; improving the way you access snippets actually matters quite a lot.

_Originally posted by @TiddlyTweeter in https://github.com/wikilabs/plugins/issues/65#issuecomment-808107038_

**Comment by pmario** [comment]
also see: https://github.com/wikilabs/plugins/discussions/56#discussioncomment-547544

**Comment by pmario** [comment]
@TiddlyTweeter

I'm so happy, that the prototype works, that I need to post it immediately ;)

![grafik](https://user-images.githubusercontent.com/374655/115395576-507e4500-a1e4-11eb-807b-1f5a0207ab94.png)

**Comment by TiddlyTweeter** [comment]
> I'm so happy, that the prototype works, that I need to post it immediately ;)

That looks excellent! I'll test as soon as its ready :-).

(P.S. - FYI, I'm busy on real life at the moment but hope to get back to CM soon.)

**Comment by pmario** [comment]
Will be part of V0.20.0-public-beta which will be published and promoted soon. 

@TiddlyTweeter ... It will contain some **breaking changes**, but it will simplify the `\customize` syntax quite a bit.

**Comment by TiddlyTweeter** [comment]
@pmario just FYI. I been working a lot with CM. It is great! I'm just very busy and gave no feedback recently. Realistically I may be able to do that in a month. I will as soon as I can. I do think it solves lots of issues ordinary users have.

A dopo, J

**Comment by pmario** [comment]
No Problem.

I've finalized the "snippet editors" now and I think they work great. ... 

I think in the end those "dropdowns" will be the only editor-buttons that experienced users use, because they are ultra-flexible, once you did take the time to create the snippets and the "button sets"

**Comment by pmario** [comment]
For V0.20.0 I did remove the `_1, _2 .. ` parameters and replaced them with `_params="""key1="value1" key2="value with spaces" """` ... So the limit with 4 "fixed" params is gone. ... Only the parameter order is important. 

So the `_params` attribute will understand the same syntax as a parameters in a `<$macrocall ` widget.

**Comment by TiddlyTweeter** [comment]
> So overall the syntax should be cleaner now. I intend to release a public-beta with some videos this weekend.

Very good! I do think it deserves _wide_ public release. It opens TW up for end users to be able to bespoke markup easily. 
I SUSPECT (excuse the capitals :-) there is a huge latent audience for this.

Best wishes
Josiah
